<?php

return [
    'activity_logs' => [
        'id' => 'id',
        'event' => '事件',
        'created_at' => '日志时间',
        'uid' => '操作用户id',
        'username' => '操作用户名',
        'user_type' => '操作用户类型',
        'subject_type' => '操作对象类型',
        'subject_id' => '操作对象id',
        'subject_name' => '操作对象名称',
        'context' => '上下文信息',
        'request_id' => '请求id',
        'request_method' => 'HTTP请求方法，命令行下为console',
        'request_url' => '请求URL，命令行下为命令完整参数',
        'route' => '路由名称或者路由URI',
        'ip' => '客户端IP地址',
    ],
    'admins' => [
        'id' => 'id',
        'username' => '用户名',
        'realname' => '姓名',
        'password' => '密码',
        'salt' => '加密盐值',
        'avatar' => '头像',
        'captcha_rule' => '验证码规则',
        'login_num' => '登录次数',
        'last_login_at' => '最后登录时间',
        'last_login_ip' => '最后登录ip',
        'v' => '数据版本号',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
        'deleted_at' => '删除时间戳',
    ],
    'failed_jobs' => [
        'id' => 'Id',
        'uuid' => 'Uuid',
        'connection' => 'Connection',
        'queue' => 'Queue',
        'payload' => 'Payload',
        'exception' => 'Exception',
        'failed_at' => 'Failed At',
    ],
    'login_logs' => [
        'id' => 'id',
        'uid' => '用户id',
        'username' => '用户名',
        'ip' => '登录ip',
        'code' => '登录返回码',
        'message' => '登录失败时的提示信息',
        'created_at' => '创建时间',
        'context' => '上下文信息',
        'request_id' => '请求id',
    ],
    'logs' => [
        'id' => 'id',
        'uid' => '用户id',
        'username' => '用户名',
        'user_type' => '用户类型',
        'message' => '日志message',
        'level' => '日志级别',
        'code' => '日志code',
        'category' => '日志分类',
        'request_id' => '请求id',
        'route' => '请求路由名称',
        'method' => '请求方法',
        'url' => '请求url',
        'context' => '日志context',
        'ip' => 'ip',
        'created_at' => '创建时间',
    ],
    'menus' => [
        'id' => 'id',
        'pid' => '父id',
        'name' => '菜单名称',
        'code' => '菜单编码',
        'path' => '菜单路径',
        'level' => '层级',
        'sort' => '排序',
        'type' => '类型',
        'enabled' => '启用',
        'visible' => '是否显示',
        'icon' => 'icon图标',
        'route' => '前端路由地址',
        'v' => '数据版本号',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
        'deleted_at' => '删除时间戳',
    ],
    'migrations' => [
        'id' => 'Id',
        'migration' => 'Migration',
        'batch' => 'Batch',
    ],
    'operation_logs' => [
        'id' => 'id',
        'event' => '事件',
        'created_at' => '日志时间',
        'uid' => '操作用户id',
        'username' => '操作用户名',
        'user_type' => '操作用户类型',
        'subject_type' => '操作对象类型',
        'subject_id' => '操作对象id',
        'subject_name' => '操作对象名称',
        'changes' => '变更内容',
        'request_id' => '请求id',
        'request_method' => 'HTTP请求方法，命令行下为console',
        'request_url' => '请求URL，命令行下为命令完整参数',
        'route' => '路由名称或者路由URI',
        'ip' => '客户端IP地址',
    ],
    'password_resets' => [
        'email' => 'Email',
        'token' => 'Token',
        'created_at' => 'Created At',
    ],
    'personal_access_tokens' => [
        'id' => 'Id',
        'tokenable_type' => 'Tokenabled Type',
        'tokenable_id' => 'Tokenabled Id',
        'name' => 'Name',
        'token' => 'Token',
        'abilities' => 'Abilities',
        'last_used_at' => 'Last Used At',
        'expires_at' => 'Expires At',
        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
    ],
    'role_admins' => [
        'id' => 'id',
        'role_id' => '角色id',
        'uid' => '管理员id',
        'created_at' => '创建时间',
    ],
    'role_menus' => [
        'id' => 'id',
        'role_id' => '角色id',
        'menu_id' => '菜单id',
        'created_at' => '创建时间',
    ],
    'roles' => [
        'id' => 'id',
        'name' => '角色名称',
        'remark' => '备注',
        'v' => '数据版本号',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
        'deleted_at' => '删除时间戳',
    ],
    'uniqids' => [
        'id' => 'id',
        'name' => '生成器名称',
        'value' => '最新值',
        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
    ],
    'upload_categories' => [
        'id' => 'id',
        'pid' => '父id',
        'name' => '分类名称',
        'path' => '分类路径',
        'level' => '层级',
        'sort' => '排序',
        'version' => '数据版本号',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
        'deleted_at' => '删除时间戳',
    ],
    'upload_logs' => [
        'id' => 'id',
        'file_id' => '文件uuid',
        'uid' => '用户id',
        'username' => '用户名',
        'user_type' => '用户类型',
        'path' => '路径',
        'url' => 'url地址',
        'name' => '显示名',
        'original_name' => '原始名',
        'size' => '大小',
        'extension' => '后缀',
        'mime_type' => 'mime类型',
        'disk' => '上传磁盘',
        'width' => '图片宽',
        'height' => '图片高',
        'category_id' => '所属分类id',
        'code' => '返回码',
        'message' => '返回信息',
        'ip' => '用户ip',
        'info' => '其它信息',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
    ],
    'uploads' => [
        'id' => 'id',
        'file_id' => '文件uuid',
        'category_id' => '所属分类id',
        'uid' => '用户id',
        'username' => '用户名',
        'user_type' => '用户类型',
        'disk' => '上传磁盘',
        'path' => '路径',
        'url' => 'url地址',
        'name' => '显示名',
        'original_name' => '原始名',
        'size' => '大小',
        'extension' => '后缀',
        'mime_type' => 'mime类型',
        'width' => '图片宽',
        'height' => '图片高',
        'ip' => '用户ip',
        'info' => '其它信息',
        'created_at' => '创建时间',
        'updated_at' => '更新时间',
        'deleted_at' => '删除时间戳',
    ],
];
